sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc

before_install:
  - sudo apt-get update && sudo apt-get install build-essential software-properties-common -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get install gcc-6 g++-6 -y 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

install:
  - echo `which $CC`
  - echo `which $CXX`
  - curl https://cmake.org/files/v3.6/cmake-3.6.1-Linux-x86_64.tar.gz | sudo tar -x -z --strip-components 1 -C /usr

script:
  - echo `which $CXX`
  - mkdir build && cd build;
    cmake -DCMAKE_CXX_COMPILER=$CXX ..
  - make lab3_smart_tree_step1_tests
  - tests/lab3test/lab3_smart_tree_step1_tests
  - make lab3_smart_tree_step2_tests
  - tests/lab3test/lab3_smart_tree_step2_tests
  - make lab3_smart_tree_step3_tests
  - tests/lab3test/lab3_smart_tree_step3_tests
  - make lab3_smart_tree_step4_tests
  - tests/lab3test/lab3_smart_tree_step4_tests
  - make lab3_smart_tree_step5_tests
  - tests/lab3test/lab3_smart_tree_step5_tests


  
notifications:
  email: false
